/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_polysfactory_scouter_jni_ScouterProcessor */

#ifndef _Included_com_polysfactory_scouter_jni_ScouterProcessor
#define _Included_com_polysfactory_scouter_jni_ScouterProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_polysfactory_scouter_jni_ScouterProcessor
 * Method:    nativeCreateObject
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_polysfactory_scouter_jni_ScouterProcessor_nativeCreateObject
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_polysfactory_scouter_jni_ScouterProcessor
 * Method:    nativeProcess
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_polysfactory_scouter_jni_ScouterProcessor_nativeProcess
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_polysfactory_scouter_jni_ScouterProcessor
 * Method:    nativeDestroyObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_polysfactory_scouter_jni_ScouterProcessor_nativeDestroyObject
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
